#!/bin/bash 

function start_master(){
    (($DEV)) && echo "start master" 
    clean_containers $MASTER_CONTAINER
    docker run -dP -t --name $MASTER_CONTAINER --cpuset-cpus=$MASTER_CPUS --net $NET -e JAVA_HOME=$JAVA_HOME --hostname $MASTER_CONTAINER $MASTER_IMAGE master 
}

function start_worker(){
    (($DEV)) && echo "start worker"
    clean_containers $WORKER_CONTAINER
    CNT=0
    while [[ ${CNT} -lt ${NUM_WORKERS} ]]; do
        if mkdir ${LOCKDIR}; then
            docker run -dP -t --net ${NET} --name ${WORKER_CONTAINER}-${CNT} -e JAVA_HOME=$JAVA_HOME --cpuset-cpus=${WORKER_CPUS[${CNT}]} --hostname ${WORKER_CONTAINER}-${CNT} ${HADOOP} slave
            rm -rf ${LOCKDIR}
        fi
	CNT=$((CNT+1))
    done
}

function detect_stage(){
    case "$1" in
    warmup)
        KEYWORDS="Mahout: seqwiki"
        log_helper_stdout ${CLIENT_CONTAINER} "${KEYWORDS}" 2
        (($DEV)) && echo "Warm up completed"
        ;;
    finished)
	KEYWORDS="completed successfully"
        log_helper_stdout ${CLIENT_CONTAINER} "${KEYWORDS}" 2
        (($DEV)) && echo "Finished"
        ;;
    esac
}

function log_client(){
    docker logs $CLIENT_CONTAINER >> $CLIENT_LOG 
}

function client_summary(){
    # grep "" $CLIENT_LOG >> $CLIENT_SUMMARY
    grep took $CLIENT_LOG >> $CLIENT_SUMMARY
    # cat $PERF_LOG | awk '{printf "%15s\n",$1}' >> $CLIENT_SUMMARY
}
