#!/bin/bash 

function start_master(){
    (($DEV)) && echo "start master" 
    clean_containers $MASTER_CONTAINER
    docker run -dP -t --name $MASTER_CONTAINER -v $WIKI_FILE:/root/wiki -v $CWD/files/mapred-site.xml:/opt/hadoop-2.9.1/etc/hadoop/mapred-site.xml --cpuset-cpus=$MASTER_CPUS --net $NET -e JAVA_HOME=$JAVA_HOME --hostname $MASTER_CONTAINER $MASTER_IMAGE master 
}

function start_worker(){
    (($DEV)) && echo "start worker"
    clean_containers $WORKER_CONTAINER
    docker run -dP -t --net ${NET} --name ${WORKER_CONTAINER}-0 -v $CWD/files/yarn-site.xml:/opt/hadoop-2.9.1/etc/hadoop/yarn-site.xml -e JAVA_HOME=$JAVA_HOME --cpuset-cpus=${WORKER_CPUS[0]} --hostname ${WORKER_CONTAINER}-0 ${HADOOP} slave
}

function detect_stage(){
    case "$1" in
    warmup)
        KEYWORDS="Mahout: seqwiki"
        log_helper_stdout ${CLIENT_CONTAINER} "${KEYWORDS}" 2
        (($DEV)) && echo "Warm up completed"
        ;;
    finished)
	KEYWORDS="completed successfully"
        log_helper_stdout ${CLIENT_CONTAINER} "${KEYWORDS}" 2
        (($DEV)) && echo "Finished"
        ;;
    esac
}

function log_client(){
    docker logs $CLIENT_CONTAINER >> $CLIENT_LOG 
}

function client_summary(){
    grep took $CLIENT_LOG >> $CLIENT_SUMMARY
    # cat $PERF_LOG | awk '{printf "%15s\n",$1}' >> $CLIENT_SUMMARY
}
