#!/bin/bash 

function start_master(){
    (($DEV)) && echo "start master" 
    clean_containers $MASTER_CONTAINER
    # docker run -dP -t --name $MASTER_CONTAINER -v $WIKI_FILE:/root/wiki -v $CWD/files/mapred-site.xml:/opt/hadoop-2.9.1/etc/hadoop/mapred-site.xml --cpuset-cpus=$MASTER_CPUS --net $NET -e JAVA_HOME=$JAVA_HOME --hostname $MASTER_CONTAINER $MASTER_IMAGE master 
    docker run -dP -t --name $MASTER_CONTAINER --cpuset-cpus=$MASTER_CPUS --net $NET -e JAVA_HOME=$JAVA_HOME --hostname $MASTER_CONTAINER $MASTER_IMAGE master
}

function start_worker(){
    (($DEV)) && echo "start worker"
    clean_containers $WORKER_CONTAINER
    # docker run -dP -t --net ${NET} --name ${WORKER_CONTAINER} -v $CWD/files/yarn-site.xml:/opt/hadoop-2.9.1/etc/hadoop/yarn-site.xml -e JAVA_HOME=$JAVA_HOME --cpuset-cpus=${WORKER_CPUS} --hostname ${WORKER_CONTAINER} ${HADOOP} slave
    docker run -dP -t --net ${NET} --name ${WORKER_CONTAINER} -e JAVA_HOME=$JAVA_HOME --cpuset-cpus=${WORKER_CPUS} --hostname ${WORKER_CONTAINER} ${HADOOP} slave
}

function detect_stage(){
    case "$1" in
    warmup)
        KEYWORDS="Mahout: seqwiki"
        log_helper_extern ${CLIENT_LOG2} "${KEYWORDS}" 1 
        (($DEV)) && echo "Warm up completed"
        ;;
    finished)
	KEYWORDS="Benchmark time:"
        log_helper_extern ${CLIENT_LOG2} "${KEYWORDS}" 2
        (($DEV)) && echo "Finished"
        ;;
    esac
}

function log_client(){
    docker logs $CLIENT_CONTAINER >> $CLIENT_LOG 
}

function client_summary(){
    grep "Benchmark time" ${CLIENT_LOG2} >> $CLIENT_SUMMARY
    grep "took " $CLIENT_LOG | awk '{print $7}' >> $CLIENT_SUMMARY
}
