import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

path="/home/ztian/cloudsuite-tuning/web-search/"
cavium = pd.read_csv(path+"2-threaded-cavium/summary.csv")
intel = pd.read_csv(path+"2-threaded-intel/summary.csv")

# Columns: Index(['Operations', 'avg', 'cycles', 'instructionsK', 'instructionsU', 'ipcK','ipcTotal', 'ipcU', 'p90th', 'p99th', 'throughput', 'totalOps'],

# sub = plt.subplot(1,2,1)
# plt.plot(cavium['Operations'][0:20], cavium['p90th'][0:20], label="p90th", linestyle='None', marker=".")
# plt.plot(cavium['Operations'][0:20], cavium['p99th'][0:20], label="p99th", linestyle='None', marker=".")
# plt.plot(cavium['Operations'][0:20], cavium['avg'][0:20], label="Avg", linestyle='None', marker=".")
# plt.xlabel("Threads")
# plt.ylabel("Latency [s]")
# plt.title("Latency for Two-threaded Cavium")
# # sub.set_yticks(np.arange(0,0.55,0.05))
# sub.set_ylim([0,2])
# sub.set_yticks(np.arange(0,2,0.1))
# sub.set_xticks(np.arange(40,610,30))
# plt.grid(linestyle="dotted")
# plt.legend()

# sub2 = plt.subplot(1,2,2)
# plt.plot(intel['Operations'][1:20], intel['p90th'][1:20], label="p90th", linestyle="None", marker=".")
# plt.plot(intel['Operations'][1:20], intel['p99th'][1:20], label="p99th", linestyle="None", marker=".")
# plt.plot(intel['Operations'][1:20], intel['avg'][1:20], label="Avg", linestyle="None", marker=".")
# plt.xlabel("Threads")
# plt.ylabel("Latency [s]")
# plt.title("Latency for Two-threaded Intel")
# sub2.set_ylim([0,2])
# sub2.set_yticks(np.arange(0,2,0.1))
# sub2.set_xticks(np.arange(40,610,30))
# plt.grid(linestyle="dotted")
# plt.legend()

sub = plt.subplot(3,1,1)
plt.plot(cavium['Operations'][0:20], cavium['p90th'][0:20], label="Cavium", linestyle='None', marker=".")
plt.plot(intel['Operations'], intel['p90th'], label="Intel", linestyle="None", marker=".")
plt.xlabel("Threads")
plt.ylabel("90th Percentile Latency [s]")
# plt.title("90th percentile latency")
# sub.set_yticks(np.arange(0,0.55,0.05))
sub.set_xticks(np.arange(10,610, 30))
plt.grid(linestyle="dotted")
plt.legend()

sub2 = plt.subplot(3,1,2)
# print(cavium['p99th'][0:20])
# print(intel['p99th'][0:20])
plt.plot(cavium['Operations'][0:20], cavium['p99th'][0:20], label="Cavium", linestyle='None', marker=".")
plt.plot(intel['Operations'], intel['p99th'], label="Intel", linestyle="None", marker=".")
plt.xlabel("Threads")
plt.ylabel("99th Percentile Latency [s]")
# plt.title("99th percentile latency")
# sub2.set_yticks(np.arange(0,1.5,0.05))
sub2.set_xticks(np.arange(10,610, 30))
plt.grid(linestyle="dotted")
plt.legend()

sub3 = plt.subplot(3,1,3)
# print(cavium['p99th'][0:20])
# print(intel['p99th'][0:20])
plt.plot(cavium['Operations'][0:20], cavium['avg'][0:20], label="Cavium", linestyle='None', marker=".")
plt.plot(intel['Operations'], intel['avg'], label="Intel", linestyle="None", marker=".")
plt.xlabel("Threads")
plt.ylabel("Average Latency [s]")
# plt.title("Average latency")
# sub2.set_yticks(np.arange(0,1.5,0.05))
sub3.set_xticks(np.arange(10,610, 30))
plt.grid(linestyle="dotted")
plt.legend()

plt.show()
