#!/bin/bash 

function start_server(){
    (($DEV)) && echo "start server"
    clean_containers $SERVER_CONTAINER
    docker run -d --name ${SERVER_CONTAINER} --cpuset-cpus=${SERVER_CPUS} --net $NET $SERVER_IMAGE -t $SERVER_NUM -m $SERVER_MEM -n 550
}

function start_client(){
    (($DEV)) && echo "start client"
    docker run -v ${CWD}/files/docker-entrypoint.sh:/entrypoint.sh -v ${CWD}/files/servers.txt:/usr/src/memcached/memcached_client/servers.txt --net $NET --name $CLIENT_CONTAINER --cpuset-cpus=${CLIENT_CPUS} $CLIENT_IMAGE $DATASET_SCALE $WORKER_NUM $TARGET_RPS
}

function detect_stage () {
    case "$1" in
    warmup)
        KEYWORDS="You are warmed up"
        log_helper_stdout ${CLIENT_CONTAINER} "${KEYWORDS}"
        ;;
    *)
        printf "Unrecognized option for stage $1:\n \
            master-ready, workers-ready, ramp-up, finished"
        exit 1
    esac
}

function log_client(){
    docker logs $CLIENT_CONTAINER 2>/dev/null | sed -n -e '/warm/,$p' > $CLIENT_LOG
    cat out/perf.txt | awk '{printf "%15s\n",$1}' >> $CLIENT_SUMMARY 
}

function latency_summary(){
    echo "median 95th latency" >> $CLIENT_SUMMARY
    cat out/client-result.txt | grep -A1 95th | grep -v 95th | awk '{print $10}'| sed '/^$/d' | sort | sed -n "$((MEASURE_TIME/2))p" >> $CLIENT_SUMMARY
}

function rps_summary(){
    echo "median achieved rps" >> $CLIENT_SUMMARY
    cat out/client-result.txt | grep -A1 95th | grep -v 95th | awk '{print $2}'| sed '/^$/d' | sort | sed -n "$((MEASURE_TIME/2))p" >> $CLIENT_SUMMARY
    #echo "min achieved rps" >> $CLIENT_SUMMARY
    #cat out/client-result.txt | grep -A1 95th | grep -v 95th | awk '{print $2}'| sed '/^$/d' | sort | sed -n '1p' >> $CLIENT_SUMMARY
}
